### ISSUE TITLE
Change the subscribe/unsubscribe functions

### ISSUE THREAD

**Issue by matheusml** [concretesolutions/redux-zero#10]
As noticed in this [comment](https://medium.com/@drcmda/this-looks-fantastic-just-two-little-nitpicks-d5234038921d?source=email-fb33cb80b669-1507840153158-activity.response_created) we can have a hard time with anonymous functions using the currect pattern.

**Comment by malbernaz** [comment]
```js
subscribe(f) {
  listeners.push(f)
  
  return () => {
    listeners.splice(listeners.indexOf(f))
  }
}
```
This would do the trick. Plus removing the unsubscribe method from the store.

**Comment by matheusml** [comment]
I'll have to test this, but it looks promising (and Redux-like)
