### ISSUE TITLE
Is there a way to compatible with redux middleware?

### ISSUE THREAD

**Issue by axetroy** [concretesolutions/redux-zero#105]
Anyway. redux got a lot of middleware in community, many of them is powerful and useful.

If it is compatible, It must be pretty cool.

It mean **people don't need to rewrite their middleware** and ``redux-zero` can use it well.

This will surely attract a lot of people to use.

**Comment by matheusml** [comment]
Hi @axetroy, thanks for the question.

We now have a [middleware](https://github.com/concretesolutions/redux-zero#middleware). You can plug in anything you want.

**Comment by axetroy** [comment]
@matheusml 
thanks, I got it.
I have write a middleware, maybe it can help people.

[redux-zero-logger](https://github.com/axetroy/redux-zero-logger)
[redux-zero-persist](https://github.com/axetroy/redux-zero-persist)
