### ISSUE TITLE
Separate modules

### ISSUE THREAD

**Issue by bl-brandon** [concretesolutions/redux-zero#106]
Great work! Was working on something similar myself, and this library fit the need just right! 

I was wondering if it was possible to separate out the different modules? As I need to only install the react specific code. 

Trying to keep my bundle sizes to a minimum.

**Comment by matheusml** [comment]
Hi @bl-brandon, thanks for the question.

We already do that.

When you do this:

```js
import createStore from "redux-zero"
import { Provider, connect } from "redux-zero/react"
```

you're already importing only the bundle you'll need for react.
