### ISSUE TITLE
How do you pass arguments to an action?

### ISSUE THREAD

**Issue by dlee** [concretesolutions/redux-zero#111]
The docs don't give an example of how you can pass an argument into actions. Is it even possible?

**Comment by matheusml** [comment]
Yes, it's possible.

Please take a look at the [unit tests](https://github.com/concretesolutions/redux-zero/blob/master/src/react/components/connect.spec.tsx#L71). There's an example with an increment function with parameters.

But you're right, we need to add this to the DOCs.
