### ISSUE TITLE
Any ports for redux undo redo?

### ISSUE THREAD

**Issue by mspanish** [concretesolutions/redux-zero#118]
Hello has anybody had the need to port any of the libs for redux undo redo to redux-zero?  This one looks pretty nice- [Redux Undo](https://github.com/omnidan/redux-undo).

**Comment by matheusml** [comment]
For Redux it's easier because it does not modify the state directaly, but create a new one, which makes waaaay easier to time-travel, for example.

We're thinking in some ways to do the same with Redux Zero, but right now it's for the future.
