### ISSUE TITLE
Split the project

### ISSUE THREAD

**Issue by matheusml** [concretesolutions/redux-zero#12]
Right now the project is coupled with React.
We should split the project so that we can have React, Preact, Angular and Vue bindings, for example.

**Comment by developit** [comment]
This could also be done with multiple entry points:

```js
import createStore from 'redux-zero';
import { Provider, connect } from 'redux-zero/preact';  // maybe just ESM

export default () => (
  <Provider store={createStore()}><App /></Provider>
);

const mapStateToProps = ({ count }) => ({ count });

const App = connect(mapStateToProps)( ({ count }) => (
  <button>{count}</button>
));
```

**Comment by matheusml** [comment]
I was thinking something more like Redux:

```
import createStore from 'redux';
import { Provider, connect } from 'react-redux';
```

But this looks even better! I'll check if Rollup can easily handle this, if not maybe change to Webpack...

Quick question: what about UMD with multiple entry points? I'm guessing that'll be something like this:

```
<script src="https://unpkg.com/redux-zero/dist/redux-zero.min.js"></script>
<script src="https://unpkg.com/redux-zero/dist/redux-zero/preact.min.js"></script>
```

**Comment by developit** [comment]
It can get a bit messy - that'd be the drawback.  If you're up for maintaining the 3-4 repos for each lib than that's probably the safe route haha.

**Comment by matheusml** [comment]
Btw, something that is concerning me with this approach are the peerDeps.
Right now we have React as a peer dependency, which means that React will be implicitly added to the final build. With this approach it's not going to be possible to have peerDeps, this can cause trouble in the future.
