### ISSUE TITLE
Middleware?

### ISSUE THREAD

**Issue by DarrylD** [concretesolutions/redux-zero#13]
First off, I love the concept and the simplicity of it. I often found myself annoyed with reducers because the project is so small. 

With that said, things like redux-sagas and redux-observables seem to offset the need for reducers. Wonder would would be a simple way to introduce a form of middleware without the bloat. My first inclination is composing actions, but not sure if you had a better idea in mind?

I guess I'm looking for a way to do async actions.

**Comment by matheusml** [comment]
Hi @DarrylD 

First, thanks for the compliments! 
Redux Zero actions are just JavaScript functions. If you want async actions, I don't see why you can't just use async(await) functions.
My concern with adding more stuff to the library, is that one day we end up exactly like Redux, you know?

Thanks for the message!

**Comment by matheusml** [comment]
I'm closing this one. If you have any other questions please feel free to ask.

**Comment by DarrylD** [comment]
Valid points. That was my Friday brain talking 😁

**Comment by axetroy** [comment]
@matheusml 
Can I use redux middleware? example,  redux-persist

**Comment by matheusml** [comment]
@axetroy could you describe in more details what you mean by that?

**Comment by DarrylD** [comment]
@axetroy i think something like that would need to be recreated with actions. 

But, I do think it may be a good idea to implement something that allows you to use the many redux middleware libs. Part of the buy in for redux is the ecosystem.

**Comment by axetroy** [comment]
@DarrylD 
yeah. redux ecosystem is complete. got many middleware.

If redux-zero can reuse it. that must be awesome and powerful.

**Comment by axetroy** [comment]
@matheusml 
I mean, support redux middleware, many should happy to see that.

redux community have a lot of superior middleware.
many of them will not rewrite again just for compatibility with redux-zero.

**Comment by matheusml** [comment]
What you suggesting is something like this:

```javascript
import createStore from 'redux-zero'

const initialState = { count: 0 }
const store = createStore(initialState, middleware)

export default store
```

We can have an optional parameter to `createStore` that accepts external middlewares, but without implementing any specific middleware to Redux Zero.

Is that right?

**Comment by axetroy** [comment]
@matheusml 
damn right!:+1:

**Comment by matheusml** [comment]
Seems awesome to me. Any of ( @axetroy, @DarrylD ) you want to take it?
I just created the issue #36

**Comment by DarrylD** [comment]
I'm still swamped with work (like the render-prop feature I wanted to tackle 😂). Hopefully, I'll have time soon.

**Comment by renatorib** [comment]
The redux middlewares relies on redux dispatch that's a simple/raw object with `type` and other inputs.
Middlwares can easily track these dispatch inputs, as well as their types.

Redux-zero don't have dispatchs, it's a simple sotre with `setState` and `getState`

I guess it's impossible to port some redux middleware to redux-zero.
