### ISSUE TITLE
Render props

### ISSUE THREAD

**Issue by DarrylD** [concretesolutions/redux-zero#14]
With the big push to [render props](https://www.youtube.com/watch?v=BcVAq3YFiuc) wonder if it would be a good idea to add a render-prop variant. Something like this...

```javascript
import React from "react";
import { connect } from "redux-zero";

import { increment, decrement } from "./actions";

const mapToProps = ({ count }) => ({ count });

export default () => (
    <Connect mapToProps={mapToProps}>
        {({ count }) =>
            <div>
                <h1>{count}</h1>
                <div>
                    <button onClick={increment}>increment</button>
                    <button onClick={decrement}>decrement</button>
                </div>
            </div>
        }
    </Connect>
);
```

**Comment by matheusml** [comment]
That's a wonderful idea. I think we should go for it!

**Comment by DarrylD** [comment]
Under a tight deadline, once I come up for air I can take a stab at a PR if nobody else does.

**Comment by matheusml** [comment]
It's yours @DarrylD 

Thanks!

**Comment by dmmulroy** [comment]
@DarrylD I took a first shot at this, would love feedback on my PR as I've never built a render callback component! Could probably also use some better TS support. 

See #26
