### ISSUE TITLE
Add Preact bindings

### ISSUE THREAD

**Issue by matheusml** [concretesolutions/redux-zero#20]
Now that `createStore` is decoupled from `Provider` and `connect` we can add preact bindings.

**Comment by matheusml** [comment]
@malbernaz is taking this, right?

**Comment by rafaesc** [comment]
Hi @matheusml, I'd like to take this

**Comment by matheusml** [comment]
Sorry @rafaesc but I'm pretty sure that @malbernaz is almost done on this one :(

**Comment by rafaesc** [comment]
ok @matheusml, no problem

**Comment by matheusml** [comment]
Hey @rafaesc do you still want this?

**Comment by matheusml** [comment]
Hi @malbernaz 

Is there something that I could help on your PR?
