### ISSUE TITLE
Computed equivalent?

### ISSUE THREAD

**Issue by bestguy** [concretesolutions/redux-zero#23]
Great project.  I frequently use [MobX computed values](https://mobx.js.org/refguide/computed-decorator.html) to have derived values from the mutable state.

Can you recommend or explain the equivalent to derived values using redux-zero?
Should I store computed values in store state? Or use listeners in some way?

Thanks

**Comment by malbernaz** [comment]
hey @bestguy, I've never used mobX to be honest, but for that purpose I suppose you can make a computed property in the mapToProps function passed to the `connect` HOC, like so:

```js
const mapToProps = (state) => ({ name: state.firstName + " " + state.lastName })

const Comp = connect(mapToProps)(({ firstName }) => <span>hello {firstName}!</span>)
```

It would probably make sense to implement some kind of caching if you want to use this more extensively though.

**Comment by matheusml** [comment]
Hi @bestguy 

Are you ok with @malbernaz 's answer? Do you still have a doubt about computed values?

**Comment by bestguy** [comment]
Yes thanks, I'm fine closing.  Answer is not exactly what I'd "like" in that the derived data is then defined in the component vs store, but this helps, thanks.
