### ISSUE TITLE
Create an example with SSR

### ISSUE THREAD

**Issue by matheusml** [concretesolutions/redux-zero#25]
Discussed here #22

**Comment by Guru107** [comment]
I can take this up?

**Comment by matheusml** [comment]
Yeah @Guru107. It's yours. :100:

**Comment by matheusml** [comment]
Hi @Guru107 

Can I help you with this one?

**Comment by Guru107** [comment]
Hey @matheusml was caught up in other work wasn't able to look at it. I m planning to getting it done over the weekend. Will definitely bug you if I need any help. Cheers 👍

**Comment by Guru107** [comment]
Hey @matheusml check out the [Repo](https://github.com/Guru107/redux-zero-ssr-example) . Let me know your feedback.

**Comment by malbernaz** [comment]
@Guru107 this is looking awesome!

**Comment by matheusml** [comment]
This is awesome @Guru107 

Please add this to the `examples/react` folder!

**Comment by Guru107** [comment]
@matheusml this issue can be closed
