### ISSUE TITLE
does not work with immutable.js object as state

### ISSUE THREAD

**Issue by Yevs** [concretesolutions/redux-zero#31]
Due to object destructuring in `createStore` immutable.js objects are losing some of their methods, e.g. `Map` loses `getIn`, `setIn` etc.

**Comment by matheusml** [comment]
Thanks for the warning @Yevs 

Do you have something in mind for the possible solution?

**Comment by Yevs** [comment]
if you are ok with breaking the current API, we might not merge updated state into current state but just update current state with updated state, e.g.:
```
setState(update) {
      state =
        typeof update === "function"
          ? update(state)
          : update

      listeners.forEach(f => f(state))
    }
```

**Comment by matheusml** [comment]
Right now, this is what we get:

```javascript
const state = { one: { two: { three: "four" } }, five: "six" }
store.setState(state) 
expect(store.getState()).toEqual({
  one: { two: { three: "four" } },
  five: "six"
})

store.setState({ five: "seven" })
expect(store.getState()).toEqual({
  one: { two: { three: "four" } },
  five: "seven"
})
```

With this new approach that you're suggesting, this is what is going to happen:

```javascript
const state = { one: { two: { three: "four" } }, five: "six" }
store.setState(state) 
expect(store.getState()).toEqual({
  one: { two: { three: "four" } },
  five: "six"
})

store.setState({ five: "seven" })
expect(store.getState()).toEqual({
  five: "seven"
})
```
This means that we're pretty much losing the state history. Are you aware of that?

**Comment by Yevs** [comment]
Yeah, I understand, that's why I said that this will break current API. If you want to save this behavior we can just add something like `import { createStore } from 'redux-zero/replace-store-state-or-whatever'` for immutablejs users

**Comment by matheusml** [comment]
@Yevs that's an interesting approach. What you think about this @malbernaz ?

**Comment by malbernaz** [comment]
I think we can support immutablejs specifically. Not sure about other libraries.

**Comment by matheusml** [comment]
Maybe the same API of regular `createStore`, but you can import it like this:

```javascript
import createStore from 'redux-zero/immutable'
```

Wanna go for it @Yevs?

**Comment by malbernaz** [comment]
Thinking about it more in depth I think this is out of scope : /.

We should think of how trivial would it be to implement this in the code we already have. For instance, how would `store.setState` work?

In `redux` is fine to use `immutable` because the state is not manipulated directly.

And more: if we want to use `immutable` in the store today we can do it as we do in a react component state, like:

```js
this.setState(({ data }) => ({
  data: data.update('password', password =>  event.target.value)
}));
```

I'm almost sure this works. It would be nice if we had tests for this use case.

What do you think @matheusml ?

**Comment by matheusml** [comment]
Good point @malbernaz 

@Yevs let's say that we add another function to the Store, `immutableSetState`. And this function will be exactly like you proposed:

```javascript
immutableSetState(update) {
  state =
    typeof update === "function"
      ? update(state)
      : update

  listeners.forEach(f => f(state))
}
```

How is the application going to work if you're not saving the state history? Could please guide me here, because I'm not very familiar with Immutable.js?

**Comment by Yevs** [comment]
@matheusml  I am not actually sure about what you mean by "saving the state history" but I will explain how I see it functioning. It would work in a similar way to how regular redux works, e.g. current state goes through some business logic and then new state is returned: `onClick() -> store.getState() -> state -> update(state) -> newState -> store.immutableSetState(newStore) -> rerender react`. In such way redux-zero can hold anything as its state (regular js object, immutablejs object, string etc.)

**Comment by matheusml** [comment]
@Yevs thanks a lot for the time, but I think that this is out of scope **for now**.
We have some other priorities right now, and maybe in the future we can talk more in depth about this again, ok?

**Comment by Yevs** [comment]
No problem, thank you guys for such a great library! :+1:

**Comment by matheusml** [comment]
Thank you @Yevs 

And we get back to this, I'll make sure you're involved.

:100:
