### ISSUE TITLE
Is redux-zero compatible with React Native ?

### ISSUE THREAD

**Issue by dancomanlive** [concretesolutions/redux-zero#32]
Let's find out...

**Comment by guilhermefloriani** [comment]
I started a new app yesterday and the counter example was working fine for me.

<img width="890" alt="screen shot 2017-10-26 at 08 56 51" src="https://user-images.githubusercontent.com/4841110/32049419-bcb1b544-ba2b-11e7-9b28-3c204a3615e0.png">

**Comment by matheusml** [comment]
@guilhermefloriani could you please send this example in a PR? This will help a lot!
Please take a look at this issue #35
