### ISSUE TITLE
Create middleware

### ISSUE THREAD

**Issue by matheusml** [concretesolutions/redux-zero#36]
#13

**Comment by renatorib** [comment]
As I said here https://github.com/concretesolutions/redux-zero/issues/13#issuecomment-343637643 I think it's not possible to make a redux middleware work with redux-zero.

Maybe redux-zero can have your own middleware system, but I can not think of a practical application, since actions are pure functions.

**Comment by matheusml** [comment]
Thanks for this @renatorib 

What you think, @axetroy, @DarryID ?

**Comment by Kiho** [comment]
@matheusml This looks very good for me can we try to make middleware  to handle API calls?

**Comment by matheusml** [comment]
What you mean by that @Kiho?
Could you describe it with more details?

**Comment by Kiho** [comment]
I will create a sample project in couple of days. I am think about to convert async actions to middleware.

**Comment by Kiho** [comment]
Hi @matheusml I create sample project here https://github.com/Kiho/redux-zero/blob/middleware/examples/svelte/middleware/src/middleware/promise-middleware.ts to handle CRUD operation with @renatorib 's redux-zero middleware implementation.
It's not done and my method detection is not great but I think it's enough to show what it is. 
Please check it out and let me know what do you think.

**Comment by matheusml** [comment]
Hi @Kiho 

Thanks for sending this.
So, @malbernaz improved the way we handle async actions a few days. [Please take a look](https://github.com/concretesolutions/redux-zero/pull/76).

With that said, comparing to this solutions with middlewares, in my opinion, I really prefer @malbernaz's version.

**Comment by Kiho** [comment]
Hi @matheusml,
I am not suggesting to replace  @malbernaz 's async action, just suggest you to ask  @renatorib to PR his mddileware system to redux-zero to give more flexiblity to consumers https://gist.github.com/renatorib/7364524579f5dbbc302030c9d1a3e7fb
This is the only part need to be added in redux-zero core is  https://github.com/Kiho/redux-zero/commit/25b8c731405394f76cb2470b4b4472efcca2b018
my middleware code is just simple sample usage of this system and you don't need to include it in the project. 
I understand async action has more granular control on flow but middleware has some advantages like no code duplication, single line of code per action, and better maintainability.

**Comment by Kiho** [comment]
@matheusml, I removed all hard coding here https://github.com/Kiho/redux-zero/blob/middleware/examples/svelte/middleware/src/middleware/promise-middleware.ts

**Comment by matheusml** [comment]
Ok, @Kiho I agree with you.

@renatorib could you please add this to the project?

**Comment by Kiho** [comment]
Hi @renatorib Please supply name as parameter `return middleware(store)(newAction, name)`

**Comment by renatorib** [comment]
Maybe I did not get it right, but, what's this `name`?

**Comment by Kiho** [comment]
Hi @renatorib, I can use name to filler actions in middleware, my code was very messy without it.
https://github.com/Kiho/redux-zero/blob/middleware/src/utils/bindActions.ts#L8
https://github.com/Kiho/redux-zero/blob/middleware/examples/svelte/middleware/src/middleware/logger-middleware.ts#L1
https://github.com/Kiho/redux-zero/blob/middleware/examples/svelte/middleware/src/middleware/promise-middleware.ts#L9

**Comment by yeojz** [comment]
Hi @matheusml 

Throwing in another possible middleware implementation for consideration.
The method signature and application was referenced from original redux middleware.

I haven't gone too much into the tests and docs yet, just wanted to throw this out and get feedback before going too much into it.

https://github.com/concretesolutions/redux-zero/compare/master...yeojz:feature/middleware

**Comment by renatorib** [comment]
Hi @Kiho 

I honestly do not like to pass the "name" of the action next to the middleware. It's name is not referenced to action itself (because it's just a pure function), but it's the bounded name, referenced in `mapToProps`. It could cause a bunch of conflicts and bugs difficult to identify, because I can bound in my whole application various actions and certainly some may have the same name. It becomes unpredictable, conflicting and insecure

**Comment by Kiho** [comment]
Hi @renatorib 

Maybe you are right. I understand possible naming collision and there is no guard for that.
But some use case like code sample above, I like to execute action selectively. 
If you have any other way to accomplish that then I would be happy.

**Comment by Kiho** [comment]
I made little bit safer version. https://github.com/Kiho/redux-zero/blob/middleware/examples/svelte/middleware/src/middleware/promise-middleware.ts

**Comment by matheusml** [comment]
@renatorib and @Kiho 

what you think about @yeojz's version? I think it's really promising

**Comment by Kiho** [comment]
Hi @matheusml 

I don't have time to test actual code now but  @yeojz's code looks very nice, specially middleware is totally pluggerable no code added to core other than place holders.

**Comment by matheusml** [comment]
Exactly @Kiho 

What about you @renatorib, do you have something to add?

**Comment by matheusml** [comment]
@yeojz could you please open a PR with this?
