### ISSUE TITLE
async/await example?

### ISSUE THREAD

**Issue by eyamenko** [concretesolutions/redux-zero#37]
Hi there,

First of all, redux-zero looks really great and simple.

Could you please provide an example with async/await or Promises?

Thanks!

**Comment by matheusml** [comment]
Thanks @eyamenko 

If you want something fast, we have an example in the unit tests. [Just check this out](https://github.com/concretesolutions/redux-zero/blob/master/src/react/components/connect.spec.tsx#L72).

But in the future, we're going to add more React examples, and of course one with async/await and promises.

**Comment by eyamenko** [comment]
Thanks @matheusml
