### ISSUE TITLE
Svelte connect & example.

### ISSUE THREAD

**Issue by Kiho** [concretesolutions/redux-zero#41]
I like to add Svelte support in redux-zero.
Please review my project and let me know what I have to do more to make PR.
https://github.com/Kiho/redux-zero
While I was making this I hit 2 problems.
1. React dependency - Svelte does not need react at all 
2. npm run format command break on windows machine(not sure maybe only me).

**Comment by matheusml** [comment]
Thanks for this @Kiho 

I do want to make a PR, but we need unit tests on what you're adding, ok?

About your problems:
1. React is not a dependency, is a peer dependency. For this to work with Svelte, just go to the `peerDependencies` in the `package.json` file and add Svelte there.
2. I don't know about this error. Could you please provide more information about this?

Thanks again!

**Comment by Kiho** [comment]
Thanks for quick response. 
I will add unit tests but it will take a while.
And below is error  I am getting on format command.
It is working fine if I change single quote to double quote.
   ` "format": "prettier --write --no-semi 'src/**/*.ts' 'src/**/*.tsx'", `
->
   `"format": "prettier --write --no-semi \"src/**/*.ts\" \"src/**/*.tsx\"",`

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\Kiho\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'format' ]
2 info using npm@4.1.1
3 info using node@v6.9.2
4 verbose run-script [ 'preformat', 'format', 'postformat' ]
5 info lifecycle redux-zero@4.2.0~preformat: redux-zero@4.2.0
6 silly lifecycle redux-zero@4.2.0~preformat: no script for preformat, continuing
7 info lifecycle redux-zero@4.2.0~format: redux-zero@4.2.0
8 verbose lifecycle redux-zero@4.2.0~format: unsafe-perm in lifecycle true
9 verbose lifecycle redux-zero@4.2.0~format: PATH: C:\Users\Kiho\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin;D:\Work\redux-zero\node_modules\.bin;C:\ProgramData\Oracle\Java\javapath;C:\Python27\;C:\Python27\Scripts;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Windows Live\Shared;C:\Program Files (x86)\Intel\OpenCL SDK\3.0\bin\x86;C:\Program Files (x86)\Intel\OpenCL SDK\3.0\bin\x64;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\Microsoft SQL Server\100\Tools\Binn\;C:\Program Files\Microsoft SQL Server\100\Tools\Binn\;C:\Program Files\Microsoft SQL Server\100\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\100\Tools\Binn\VSShell\Common7\IDE\;C:\Program Files (x86)\Microsoft Visual Studio 9.0\Common7\IDE\PrivateAssemblies\;C:\Program Files (x86)\Microsoft SQL Server\100\DTS\Binn\;C:\Program Files (x86)\Microsoft ASP.NET\ASP.NET Web Pages\v1.0\;C:\Program Files\Microsoft SQL Server\110\Tools\Binn\;C:\Program Files\Microsoft SQL Server\110\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\110\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\110\Tools\Binn\ManagementStudio\;C:\Program Files (x86)\Microsoft Visual Studio 10.0\Common7\IDE\PrivateAssemblies\;C:\Program Files (x86)\Microsoft SQL Server\110\DTS\Binn\;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files\Microsoft\Web Platform Installer\;C:\Program Files (x86)\GitExtensions\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files (x86)\Heroku\bin;C:\Program Files (x86)\git\cmd;C:\Program Files\nodejs\;C:\Program Files\Microsoft DNX\Dnvm\;C:\Program Files\Git\cmd;C:\Program Files (x86)\Skype\Phone\;C:\Program Files (x86)\Yarn\bin;C:\Program Files\dotnet\;C:\Program Files (x86)\Elm Platform\0.16\bin;C:\Users\Kiho\.dnx\bin;C:\Program Files (x86)\Microsoft VS Code\bin;D:\AppData\Local\Android\sdk\tools;D:\AppData\Local\Android\sdk\platform-tools;C:\Users\Kiho\AppData\Local\Microsoft\WindowsApps;C:\Users\Kiho\AppData\Local\atom\bin;C:\Users\Kiho\AppData\Roaming\npm;C:\Program Files\Heroku\bin;D:\MyAppData\Local\Yarn\bin;
10 verbose lifecycle redux-zero@4.2.0~format: CWD: D:\Work\redux-zero
11 silly lifecycle redux-zero@4.2.0~format: Args: [ '/d /s /c',
11 silly lifecycle   'prettier --write --no-semi \'src/**/*.ts\' \'src/**/*.tsx\'' ]
12 silly lifecycle redux-zero@4.2.0~format: Returned: code: 2  signal: null
13 info lifecycle redux-zero@4.2.0~format: Failed to exec format script
14 verbose stack Error: redux-zero@4.2.0 format: `prettier --write --no-semi 'src/**/*.ts' 'src/**/*.tsx'`
14 verbose stack Exit status 2
14 verbose stack     at EventEmitter.<anonymous> (C:\Users\Kiho\AppData\Roaming\npm\node_modules\npm\lib\utils\lifecycle.js:279:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Users\Kiho\AppData\Roaming\npm\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:877:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid redux-zero@4.2.0
16 verbose cwd D:\Work\redux-zero
17 error Windows_NT 10.0.15063
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Kiho\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "format"
19 error node v6.9.2
20 error npm  v4.1.1
21 error code ELIFECYCLE
22 error redux-zero@4.2.0 format: `prettier --write --no-semi 'src/**/*.ts' 'src/**/*.tsx'`
22 error Exit status 2
23 error Failed at the redux-zero@4.2.0 format script 'prettier --write --no-semi 'src/**/*.ts' 'src/**/*.tsx''.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the redux-zero package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     prettier --write --no-semi 'src/**/*.ts' 'src/**/*.tsx'
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs redux-zero
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls redux-zero
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by matheusml** [comment]
Well, if that solves the problem, could you please send a PR changing it?

Thanks @Kiho 👍

**Comment by Kiho** [comment]
Now my master has other changes and I think that format problem is very minor issue, maybe everybody is coding  on Mac, so I will send PR when my unit tests are ready.
Thanks.

**Comment by matheusml** [comment]
That's ok @Kiho 

No rush here :)
