### ISSUE TITLE
Update Svelte example

### ISSUE THREAD

**Issue by matheusml** [concretesolutions/redux-zero#44]
Right now, `Counter.html` is doing this:

```javascript
import { connect, getActions  }  from '../../../../../src/svelte';
```

But it should be doing this:

```javascript
import { connect, getActions  }  from 'redux-zero/svelte';
```

@Kiho, could you please change this and check if everything is working?
You should probably update the npm version from the example to 4.3.0

**Comment by Kiho** [comment]
All done, works great.
Thanks.
