### ISSUE TITLE
TypeScript module resolution

### ISSUE THREAD

**Issue by Kiho** [concretesolutions/redux-zero#47]
According to this https://github.com/Microsoft/TypeScript/issues/2568#issuecomment-308792266
looks like you need to change this entry in package.json from
  `"typings": "dist/index.d.ts"` to `"types": "dist/index.d.ts"`
I try to reference redux-zero/svelte in ts module but it does not work.
I had to change import statement `import { getActions } from 'redux-zero/dist/svelte'` to make it work.

**Comment by eyamenko** [comment]
I'm experiencing the same issue, when trying to import `Provider` module from `redux-zero/react`.

**Comment by Kiho** [comment]
I think you can do either import `redux-zero/dist/react` or change `"typings": "dist/index.d.ts"` to `"types": "dist/index.d.ts"` in package.json under node_modules/redux-zero.
second option only works until npm update in my testing.

**Comment by matheusml** [comment]
Hi @Kiho 

Thanks a lot to noticing this!
Do you want to take this bug?

**Comment by Kiho** [comment]
Hi @matheusml, I will submit PR.

**Comment by Kiho** [comment]
I tested more and found my second solution does not work, my setup for test was wrong.
So I have to use first solution for my self now. one thing I know is if I move up files in `/svelte/svelte` to  `/svelte` then works but I am not sure how I can make that at build time.
Thanks.

**Comment by dnlsngr** [comment]
While you're fixing typings, the interface for at `react/interfaces/Store.d.ts` contains an `unsubscribe` field that looks like it became private in commit `d7bce4d786c25a6b7264b835378f7ae8df8c4bc0`. If I remove it (and shuffle the typings around as @Kiho points out) then my app compiles. I'm happy to make a separate issue and submit a PR for that.

**Comment by matheusml** [comment]
@dnlsngr thanks for that!

Yes, please open a PR for that :100:

**Comment by QuantumInformation** [comment]
I'm getting

`node_modules/redux-zero/react/index"' has no exported member 'Provider'.`
![image](https://user-images.githubusercontent.com/216566/32445693-7a86c8f4-c2fe-11e7-890b-9ccb3132ecf4.png)

**Comment by QuantumInformation** [comment]
The provider is not exported, only:

![image](https://user-images.githubusercontent.com/216566/32446643-76f94222-c301-11e7-92f8-9af99846dbc7.png)
not 
![image](https://user-images.githubusercontent.com/216566/32446657-8069b634-c301-11e7-92fa-d81cd69c6bbf.png)

![image](https://user-images.githubusercontent.com/216566/32446681-91bf35d0-c301-11e7-8ac4-d91be41b74ad.png)

**Comment by matheusml** [comment]
Hi @QuantumInformation 

We're using it inside our examples folder, with the React counter example, and as you can see it's working just fine:

![Imgur](https://i.imgur.com/dQKYGur.png)

I'm not really sure what you're doing wrong here. Maybe `rm -rf node_modules` and  `npm install` again.

**Comment by QuantumInformation** [comment]
I'm using it with TypeScript

**Comment by Kiho** [comment]
Hi @matheusml,
I made PR to fix svelte definition files but I did not touch react side because issues with interfaces.
I think, apply code below and deploy interfaces folder may work, but it might be better to move that under react. it should be OK to reference that in react from all other sub react components. 
And don't have time to play with react this time.
```
  getConfig('./src/react/index.ts', 'react/index', {
    "dist/react": "react",
    "dist/interfaces": "interfaces",
    verbose: true
  }),
```

**Comment by matheusml** [comment]
Just to make it clear.

It works just fine to use this with JavaScript:

```javascript
import { connect, Connect, Provider } from 'redux-zero/react'
```

or this with TypeScript:
```typescript
import * as ReactReduxZero from 'redux-zero/react'
```

But this, with TypeScript, is currently not working:

```typescript
import { connect, Connect, Provider } from 'redux-zero/react'
```

**Comment by Kiho** [comment]
I my knowledge, `import * as ReactReduxZero from 'redux-zero/react'` only works if there is no need to resolve types in down stream or 
you may end up doing something like this `const rzr: any = ReduxZeroReact` 
Btw, if you want to include same thing for react in my PR then I need to deploy interfaces folder to node_modules. please clarify. 
I think all the complexity here came from tree structure of d.ts files which is not combined by typescript when build.

**Comment by matheusml** [comment]
You're 100% right @Kiho 

I just made a new [PR](https://github.com/concretesolutions/redux-zero/pull/57) that's solving this.
