### ISSUE TITLE
Example with react router?

### ISSUE THREAD

**Issue by QuantumInformation** [concretesolutions/redux-zero#50]
This could be quite helpful.

**Comment by matheusml** [comment]
Yes, it would.
Wanna take this @QuantumInformation ?

**Comment by guilherme6191** [comment]
Hello guys. Is this being done? If not, maybe I could help out.
@matheusml

**Comment by QuantumInformation** [comment]
I've been snowed this month

**Comment by matheusml** [comment]
@guilherme6191 and @QuantumInformation any of you still want this one?

**Comment by QuantumInformation** [comment]
yes pls

**Comment by matheusml** [comment]
Ok @QuantumInformation

**Comment by usmanmunara** [comment]
Anyone of you have used redux-zero with react-router before? I am having a problem with it. The store is emptied every time I navigate to a new page.

**Comment by matheusml** [comment]
@usmanmunara do you have a fiddle to reproduce this?

**Comment by usmanmunara** [comment]
> STORE.JS
`import createStore from 'redux-zero';

const initialState = {todos: [], user:[], error: "", currentuser:{}};
const store = createStore(initialState);

export default store;`

> ACTIONS.JS
`const actions = store => ({
    increment: state => ({ count: state.count + 1 }),
    decrement: state => ({ count: state.count - 1 })
  });
  
  export default actions;`

> ROUTER.JS
`import React from 'react';
import {BrowserRouter, Route} from 'react-router-dom';

import { App } from './App';
import { Log } from './Components/LogSign/log-sign';
import MuiThemeProvider from 'material-ui/styles/MuiThemeProvider';


const Routers = () => (
	<MuiThemeProvider>
		<BrowserRouter >
			<div>
				<Route exact path="/" component={Log}/>
				<Route exact path="/App" component={App}/>
			</div>
		</BrowserRouter>
	</MuiThemeProvider>
);

export {Routers};`

**Comment by rmlSardinha** [comment]
I'm going to try on codesand today

**Comment by rmlSardinha** [comment]
Is that what you were talking about?

https://codesandbox.io/s/github/rmlSardinha/redux-zero-router/tree/master/
https://github.com/rmlSardinha/redux-zero-router

**Comment by matheusml** [comment]
Thanks for this @rmlSardinha 

Could you please add this to the project with a PR?

**Comment by matheusml** [comment]
@rmlSardinha do you need some help?

**Comment by rmlSardinha** [comment]
Olá @matheusml, só coloquei o router junto, não sei como poderia colocar um PR para isso.
foi só um exemplo. Mas qualquer coisa se quiser, estou a disposição.

**Comment by guilherme6191** [comment]
@matheusml, guys.

Created the PR #102 for this. I had played with redux-zero and react-router, checked out @rmlSardinha's project as well and created the example in case you guys wanna use it.

Thanks.
