### ISSUE TITLE
pass payload

### ISSUE THREAD

**Issue by Gi972** [concretesolutions/redux-zero#53]
Hello guys,
I try redux zero with a input type text but I can't get the payload when I use the onChange event. it's normal or a bug?

Thanks

**Comment by matheusml** [comment]
Could you please show us the code, or even better, create a small example on codesandbox?

**Comment by Gi972** [comment]
Hello,

Yes this is the link : https://stackblitz.com/edit/react-lps2th?file=actions.js.

I take your counter for simple example.  If I want increment with 10 or other number  for example. 

Your first param return the state ok , but the second should be take my payload .

Or maybe there is a different way for this.

Thanks @matheusml

**Comment by matheusml** [comment]
Yes, there's another way. You can use the old way, before auto-bindings the actions.
In this way, you have to import the store inside your actions.

Please read it on the [old example readme](https://github.com/concretesolutions/redux-zero/blob/0a3359a7cd2317a9d92c88e3725df55f1a1f76f2/README.md)

Btw, maybe there's a way of doing it with the new way, but right now I simply don't know.
