### ISSUE TITLE
Passing parameters on actions with Render Props

### ISSUE THREAD

**Issue by matheusml** [concretesolutions/redux-zero#58]
In #53, we discussed ways to pass parameters (payload) in the actions.

For example, if we want an `increment` action, with a dynamic value to be incremented:

```jsx
<button onClick={() => increment(10)}>Increment 10</button>
```

With our current code base, this can be easily done by simple using the second argument of the `increment` function, like this:

```javascript
const actions = store => ({
  increment: (state, payload) => ({ count: state.count + payload }),
});
```

There's just one problem: this only works for the HOC `Connect`. For some reason this is not working with the render props `connect` function.

**Comment by matheusml** [comment]
Does this work fine with Svelte, @Kiho ?

**Comment by Kiho** [comment]
In svelte example this works.

actions.ts
```
export const actions = store => ({
    increment: (state, payload) => ({ count: state.count + payload }),
    decrement: state => ({ count: state.count - 1 })
});
```
Counter.html
```
    <div>
      <button on:click="increment(10, event)" class="button">+</button>
      <button on:click="decrement(event)" class="button">-</button>
    </div>
```

**Comment by Gi972** [comment]
Hello guy,
I test this morning it works I make a mistake, I make : 
the payload works

`increment: state => payload => ({ count: state.count + payload })`
instead
`increment: (state, payload) => ({ count: state.count + payload })`

an old habit...

Hum...

**Comment by Gi972** [comment]
so for the example with payload... you can use my example:
https://stackblitz.com/edit/react-lps2th?file=Counter.js

Thanks for your attention...

**Comment by matheusml** [comment]
Hi @Gi972 

I didn't understand your message, because I pretty much said the same thing.

The reason why I opened this issue, is because although passing the parameter is working just fine for HOCs (i.e. the `Connect` function) but for some reason, the same thing isn't working for the Render Props function (i.e. the `connect` function).

**Comment by matheusml** [comment]
Let me just correct myself here. I was confused about the HOC and Render Props.
The `Connect` function is the Render Props one, and it's working fine.
But the HOC, with is the `connect` function, isn't working.

**Comment by Gi972** [comment]
:-D !

I'm lost can you make a example?

**Comment by matheusml** [comment]
@Gi972 

I just made a PR with both examples working just fine.
I'm closing this.

**Comment by babakness** [comment]
I'm getting state twice, no payload
`increment = state => payload => state === payload`
// true

bug?

Version 4.8.1

**Comment by babakness** [comment]
Mis-understood "both example work fine". Only second example works per source code.

**Comment by babakness** [comment]
It is strange however that the second function does receive any parameters...
