### ISSUE TITLE
Arquitechture Question - Why Not Reducers?

### ISSUE THREAD

**Issue by yanmagale** [concretesolutions/redux-zero#6]
Hi everyone. 

First, thanks to created this project. I always searching  state management concepts and Flux Arquitechture,really like this pattern and all power that Flux returns to project.

I liked that you make with actions and stores, principally the way to use into components.

So, i have a arquitectural question: Why not reducers or other structure to contain separated the operationals can modify state?

**Comment by matheusml** [comment]
Thanks for the question. There's definitely a place for reducers, just see the huge adoption of Redux. But this project aims to be way more simple than Redux, just a single store and your actions.

With this approach you have less boilerplate, and a smaller learning curve, for example. But for more complex applications, maybe Redux your best option.

**Comment by yanmagale** [comment]
Great, thanks @matheusml :smile:
