### ISSUE TITLE
Please remove peerDependencies

### ISSUE THREAD

**Issue by aMarCruz** [concretesolutions/redux-zero#65]
For all of us using other tools than Preact (or React).

![image](https://user-images.githubusercontent.com/6636980/32680147-f1feb85a-c62e-11e7-9b7f-f6383f002bb4.png)

...and thanks for your hard work!

**Comment by matheusml** [comment]
Hi @aMarCruz 

Thanks for opening this.

So, this is tricky. If I remove the `peerDependencies` the build throws some warnings. I have to investigate more.

**Comment by aMarCruz** [comment]
Thanks!
