### ISSUE TITLE
Add documentation of action arguments

### ISSUE THREAD

**Issue by renatorib** [concretesolutions/redux-zero#66]
I had to explore the source code to find that action arguments come from the second parameter (and later) after state

```js
const increment = state => ({ count: state.count + 1 })
const incrementBy = (state, amount) => ({ count: state.count + amount })
//                          ^ this


// later
props.increment()
props.incrementBy(10 /* amount */)
``` 

Yeah, I know it's simple and I did not see any problems with choice of API (although I prefer it curried), but **it's not** intuitive. It's not something anyone can easily **guess by**.

I think that a small example of these in readme, such as incrementBy, would help people with this same problem/doubt.

Maybe we can add some other action in readme [example](https://github.com/concretesolutions/redux-zero#example). Suggestions?

**Comment by matheusml** [comment]
Hi @renatorib 
We're already on it here: #21 

But thanks for the tip anyway

**Comment by renatorib** [comment]
Oh, great. Thanks
