### ISSUE TITLE
weird TypeError with TypeScript on createStore func

### ISSUE THREAD

**Issue by k1r0s** [concretesolutions/redux-zero#71]
Given the following implementation

![image](https://user-images.githubusercontent.com/6052309/32690924-cc208a06-c6ff-11e7-9c8a-9fe4088d12ce.png)

I got this err: `Uncaught TypeError: redux_zero_1.default is not a function`

I look a little bit on the bundle settings and I found that the main file which is served by default isn't on UMD format: 

`"main": "dist/redux-zero.js",`

because of this: 

![image](https://user-images.githubusercontent.com/6052309/32691025-66a815ac-c701-11e7-9274-eb5d8a07709d.png)

I don't have too much knowledge about this. I'll keep looking but I need your help on this.

**Comment by k1r0s** [comment]
Perhabs the tests should be performed against the build output instead the source ones?

**Comment by renatorib** [comment]
I'm almost sure this is not related to TypeScript.

**Comment by k1r0s** [comment]
The question is how nobody figure about this before? May I miss something but the implementation is quite simple :/

**Comment by renatorib** [comment]
I'm using redux-zero here and it's working as expected... You can create some minimal reproduction of this bug? So I can help investigate

**Comment by matheusml** [comment]
Hi @k1r0s 

Please do as @renatorib said. We need a minimal setup here to see what's going on.
Are you using TypeScript right? But with UMD?

**Comment by k1r0s** [comment]
Nevermind, I'm using es module, I was suppose the problem was about that l because it seems really weird. I can't provide an example right now but I'll do.

**Comment by k1r0s** [comment]
I'll upload a minimal repo to actually reproduce the issue. But can be solved doing this:

![image](https://user-images.githubusercontent.com/6052309/32698946-00491434-c7ae-11e7-9352-e3251a9c9a09.png)

**Comment by k1r0s** [comment]
https://github.com/k1r0s/rzero-imports-tmp here is the code, thanks in advantage

**Comment by matheusml** [comment]
Thanks for this @k1r0s 
I'll investigate
