### ISSUE TITLE
How do you work with side effects?

### ISSUE THREAD

**Issue by seveves** [concretesolutions/redux-zero#75]
for example I have three actions that fetch data via HTTP: fetch, fetchSuccess, fetchError

is something like the following "ok"?
```
const actions = store => ({
    fetch: state => {
        const stateUpdate = { ...state, loading: true };
        fetchFromApi().then(data => store.fetchSuccess(stateUpdate, data), err => store.fetchError(stateUpdate, err));
        return stateUpdate;
    },
    fetchSuccess: (state, payload) => ({ ...state, data: payload, loading: false }),
    fetchError: (state, payload) => ({ ...state, loading: false, error: payload }),
});
```

**Comment by k1r0s** [comment]
I try to keep actions as pure as posible (state in / state out) and manage the side actions in the component with something like this to keep component as clean as posible: 

```
import { config } from 'http-decorator';

config.base = 'http://jsonplaceholder.typicode.com';

someClassInstance.someMethod('users');
// $ curl http://jsonplaceholder.typicode.com/users

}
```

**Comment by matheusml** [comment]
Hi @seveves 

That's a good question. Right now we don't have the full documentation, but we have [some examples on dealing with async functions](https://github.com/concretesolutions/redux-zero/blob/master/src/react/components/connect.spec.tsx#L103).

But, I think that your example is 100% fine.

@malbernaz have something to add here?

**Comment by seveves** [comment]
@k1r0s and @matheusml ... thank you for your answers!
I want to remove all the async http logic from my components to keep them as simple as possible but of course the actions should stay as pure as possible. As always you have to compromise. And redux-zero should stay small and simple so it's ok that the users have to find a way to go with.
But yeah ... maybe it would be helpful to have something about side effects in the documentation 👍 

When @malbernaz has nothing to add here then feel free to close this "issue".

**Comment by malbernaz** [comment]
@seveves you are thinking as if you were using redux... In redux-zero we expose the store in the actions function to better support async. You don't need to have three actions to handle a fetch request, you can do something like this:

```js
```

**Comment by seveves** [comment]
so `const actions = store => ({ ... })` is the same as `const actions = ({ getState, setState }) => ({ ... })`? Not needing the three actions sounds very nice :)

**Comment by malbernaz** [comment]
exactly the point! Rule of thumb is: if your action is async use the store methods, otherwise just use the state parameter from the action.

**Comment by matheusml** [comment]
If you have more questions @seveves feel free to ask.
For now, I'm closing this 👍

**Comment by malbernaz** [comment]
Although thinking about this example, maybe it would be nice to perform something like this:

```js
const getActions = ({ setState }) => ({
  getTodos: async () => {
    try {
      setState({ loading: true });
      
      const payload = await client.get("/todos");
      
      return { payload, loading: false };
    } catch (err) {
      return { error: payload, loading: false };      
    }
  }
});
```

And this kind of action, probably have a better testability. It could be done roughly like this:

```js
describe("todo actions", () => {
  let actions, store, listener = jest.fn(), unsubscribe;
  beforeEach(() => {
    store = createStore();
    actions = getActions(store);
    listener.mockReset();
    usubscribe = store.subscribe(listener);
  });

  it("should fetch", async () => {
    nock('http://someapi.com/')
      .get('/todos')
      .reply(200, { id: 1, title: "test stuff" } )

    await actions.fetchTodos(store.getState());

    const [LOADING, SUCCESS] = listener.mock.calls.map(([call]) => call)

    expect(LOADING.loading).toBe(true);
    expect(SUCCESS.payload).toEqual({ id: 1, title: "test stuff" })
    expect(SUCCESS.loading).toBe(false);
  });
});
```

@matheusml, your opinion please.

**Comment by matheusml** [comment]
Since async/await is what the cool kids are doing, and the readability for this case is better, I think we should do it :+1:

**Comment by PedroEsperanca** [comment]
none of the examples above seem to be working :s

Only Loading get's updated, but the other state attributes don't
