### ISSUE TITLE
redux question, Shared state?

### ISSUE THREAD

**Issue by k1r0s** [concretesolutions/redux-zero#78]
(I'm pretty new at redux, about one week)

I have two components, both need to render a list of items. 

One third component dispatch an action to update the item list which lives on the store. 

When the store get updated two listeners invoke `update` func in `Connect` component (which wraps each component)

![image](https://user-images.githubusercontent.com/6052309/32902345-6f0df0a0-caf2-11e7-943c-08011f206cb5.png)

The problem is that those components only render when there is no shallowEqual between the actual props and the current state. But the current state is shared! meaning that only the first component will be rendered!

Im doing something wrong!? (yes, but what! hehe)

**Comment by matheusml** [comment]
Thanks for opening this @k1r0s 

@malbernaz do you have something to say here?

**Comment by k1r0s** [comment]
I have to apologize, the state isn't shared between componets as long as you propertly implement `mapToProps` function in the Connect component. The thing is I need to properly understand what's going on. 

I often do this and I guess I need to explicitly deconstruct the state and pass properties down. But why do I need to this for each component that read the state?

```jsx
<Connect mapToProps={ state => state } actions={actions}> ...
```

**Comment by matheusml** [comment]
Hi @k1r0s 

Is there something we can do to help you with this one?

**Comment by k1r0s** [comment]
well, yeah, the problem/question is fulfilled. Just wana know the behavior of `mapToProps` specificly.. thanks!
