### ISSUE TITLE
how to get ownProps?

### ISSUE THREAD

**Issue by Gamesh** [concretesolutions/redux-zero#81]
```
<Provider store={store}>
    <Counter color="blue" />
</Provider>
```
if i pass a prop color="blue" to the connected component it's not accessible inside Counter component as a prop. Only props that you return from mapToProps function are passed as constructor props.
Redux passes properties as ownProps as the second argument of mapToProps function.

Is it missing from redux-zero or am i doing something wrong ?

**Comment by matheusml** [comment]
@malbernaz do you have an elegant way to handle this?

**Comment by malbernaz** [comment]
We pass ownProps as the second argument for mapToProps as well. But this props should be accessible inside a connected component. Maybe this is a bug. @Ganesh could you show us how you are connecting your component?

**Comment by Gamesh** [comment]
just tried to recreate it on a sandbox and it works, so probably it's the late hours to blame.

Would be good to have the API documented somewhere, because i only found this searching through redux documentation. It's not even in the examples. 

thanks for redux-zero, i love the simplicity

**Comment by malbernaz** [comment]
This is actually not working @Gamesh. I have identified the bug and our `connect` HOC is in fact not getting the props passed to it in our latest release.

I'll submit a PR tonight to fix that. Please hang on!

cc @matheusml

**Comment by malbernaz** [comment]
#82 solves this. @matheusml: waiting for you to merge it.

**Comment by Gamesh** [comment]
thanks for double checking and fixing 👍
