### ISSUE TITLE
Export bindActions function

### ISSUE THREAD

**Issue by jawadst** [concretesolutions/redux-zero#86]
Hey,

My use case is the following: I have a library that uses Preact and exposes a public interface on the `window` object. The library itself creates some components and allows the webpage to interact with them through functions on `window.Library`.

For instance, calling `window.Library.openDialog()` should render a Preact component.
I need to execute actions from that `openDialog` function that is not connected to the store through a `Connect` component. Effectively, I am looking for bound actions that I can run from outside the Preact/Redux zero environment.

I am thinking that you could export the `bindActions` function and I can create those bound actions when I need to.

Any opinion on that? Let me know if you think there is a better approach to this.

Thanks a lot for this great library!
Jawad

**Comment by matheusml** [comment]
Hi @jawadst 

Thanks for opening this.

Could you please describe your use case with more code?
I'm having a hard time trying to see what the problem is.

**Comment by jawadst** [comment]
@matheusml 

Sure. I think the simplest code sample would be something like:

```javascript
import { h, render } from 'preact';
import createStore from 'redux-zero';
import { Provider } from 'redux-zero/preact';

const store = createStore({ count: 0 });

const actions = store => ({
  decrement: state => ({ count: state.count - 1 }),
  increment: state => ({ count: state.count + 1 })
});

render((
  <Provider store={store}>
    <App />
  </Provider>
), document.body);

// I want to be able to call actions and update the state from here (so from outside the component/provider)
// I was thinking of doing something like this (with bindActions from redux-zero)
const boundActions = bindActions(actions, store);

boundActions.increment();
```

Let me know if it's clearer.

**Comment by matheusml** [comment]
I don't know if it's a good idea to export this.

@malbernaz what you think?

**Comment by malbernaz** [comment]
It is a good idea, I think. I've stumbled at the same problem while writing unit tests.

**Comment by matheusml** [comment]
Ok, I'll add them in on the next release.

Do this works for you @jawadst:

```javascript
import { bindActions } from 'redux-zero/utils';
```

?

**Comment by jawadst** [comment]
@matheusml Yep that works great. Thanks!

**Comment by matheusml** [comment]
@jawadst please take a look at the PR

**Comment by jawadst** [comment]
@matheusml Looks good to me, thanks!
If your PRs are built and pushed somewhere, I am happy to test and confirm that it works as expected.

**Comment by matheusml** [comment]
@jawadst could you please install the latest version and check if that's what you wanted?

**Comment by jawadst** [comment]
@matheusml That works well, thanks a lot for adding this so quickly!
