### ISSUE TITLE
Add chrome dev tools

### ISSUE THREAD

**Issue by matheusml** [concretesolutions/redux-zero#87]
As discussed here #19 , now that we have a middleware, we can implement some sort of dev tools.

**Comment by Gamesh** [comment]
why not if possible make use of existing ones and integrate them.

BTW here link doesn't work

**Comment by matheusml** [comment]
@Gamesh it is possible to that.

**Comment by Kiho** [comment]
@matheusml I play with code from CodeSandbox here 
https://github.com/Kiho/redux-zero/blob/devtools/examples/react/counter/src/dev-tools.js
https://github.com/Kiho/redux-zero/blob/devtools/examples/react/counter/src/store.js
Find it out if it's useful.

**Comment by matheusml** [comment]
@Kiho could you please give a little description of what you've done?

**Comment by Kiho** [comment]
@matheusml Not much, I got the store.js from here https://codesandbox.io/s/qvnm8w597q posted from the other thread and split code to 2 piece for easier use or distribution.

**Comment by matheusml** [comment]
Hi @Kiho 

sorry about the delay, it is working just fine.
Just one question, the time travel isn't working because we're changing the state directly.

Do you think that's an issue?

**Comment by Kiho** [comment]
Hi @matheusml 
Personally I don't use redux dev-tool, so I am not sure what to say.

**Comment by matheusml** [comment]
@malbernaz what you think about this whole thread?

**Comment by malbernaz** [comment]
Might be a good idea. Redux devtools has a comprehensive API I think.

**Comment by Kiho** [comment]
@matheusml I made little improvement with code to replay state changes but I can't update back devtools UI.
https://github.com/Kiho/redux-zero/blob/devtools/examples/react/counter/src/dev-tools.js

**Comment by matheusml** [comment]
Hi @Kiho 

please add a PR with this new version.

💯

**Comment by Kiho** [comment]
Hi @matheusml 

Do you want to create new devtools project under examples/react folder or overwrite current counter example? You should understand a lot of things are missing here.

**Comment by matheusml** [comment]
I'm not thinking about the examples folder, I'm thinking about adding [this piece of code](https://github.com/Kiho/redux-zero/blob/devtools/examples/react/counter/src/dev-tools.js) to the project.

Do you know what I mean?

**Comment by Kiho** [comment]
You mean set it up src/devtools and serve as redux-zero/devtools ?
Or explain to me if you think other way.

**Comment by matheusml** [comment]
Yes @Kiho 

I'm thinking we should export the devtools just like you said it.
