### ISSUE TITLE
React connect decorator prevents hot module reloading

### ISSUE THREAD

**Issue by jetako** [concretesolutions/redux-zero#97]
The react/connect decorator prevents webpack and react-native hot module reloading. As far as I'm aware, React HMR doesn't work with pure functional components. This is an easy fix, simply change the innermost return value of `connect()` to a class instead of a function:

```javascript
export default function connect(mapToProps, actions = {}) {
  return Child => (
    class ConnectWrapper extends React.Component<any> {
      render() {
        const { props } = this

        return (
          <Connect {...props} mapToProps={mapToProps} actions={actions}>
            {mappedProps => <Child {...mappedProps} {...props} />}
          </Connect>
        )
      }
    }
  )
}
```

I think this would go a long way towards adoption of redux-zero, which I absolutely love!

**Comment by matheusml** [comment]
Thanks for this @jetako 

Could you send this PR?

**Comment by jetako** [comment]
Sure @matheusml, I'll send over a PR shortly :)
